### ISSUE TITLE
Add support for incubator

### ISSUE THREAD

**Issue by h-teske** [gini/gini-api-ruby#12]
It would be awesome, to also use the incubator-api:
http://developer.gini.net/gini-api/html/incubator.html

**Comment by dkerwin** [comment]
Absolutely. Lots of new and interesting extractions available. I'll add it to the next release

**Comment by dkerwin** [comment]
Supplying a custom version is already implemented. Some tweaks on the Gini API required to support the incubator on all calls. Should be available soon.
