### ISSUE TITLE
Gini::Api::Document.extractions() should take incubator parameter into account for caching

### ISSUE THREAD

**Issue by Trundle** [gini/gini-api-ruby#20]
The document object caches the extractions and always returns the same ones. Unfortunately, it does not take differing `incubator` arguments into account. This can be a bit surprising:

```ruby
# Will fetch the non-incubator extractions and cache them
doc.extractions[:amountToPay]
# Will still return the non-incubator extractions and hence that key is missing
doc.extractions(true)[:senderName]
```

**Comment by dkerwin** [comment]
You have a valid point there. I'll extend extractions and layout methods to support cache invalidation.
